<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>fyiReporting.CRI</RootNamespace>
    <AssemblyName>RdlCri</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RdlEngine\RdlEngine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BarcodeLib" Version="2.4.0" />
    <PackageReference Include="ZXing.Net" Version="0.16.6" />
    <PackageReference Include="System.Text.Json" Version="5.0.2" />
  </ItemGroup>
</Project>